spring.application.name=hrm-payroll

spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8080

# Use Base64 encoded key (important for security)
jwt.secret=bXlzZWNyZXRrZXkxMjM0NTZteXNlY3JldGtleTEyMzQ1Ng==


#logging.level.org.hibernate.SQL=DEBUG